The scope of the unsafe blocks can be appropriately reduced
Ralith/hecs pull request #260
Opened 2022-05-03 08:12 UTC by peamaeq

2022-05-04 03:33 UTC, Ralith commented
Thanks! Please run `cargo fmt`.

2022-05-05 01:21 UTC, peamaeq commented
> Thanks! Please run `cargo fmt`.
OK✔

2022-05-05 03:45 UTC, Ralith requested changes

2022-05-05 03:45 UTC, Ralith commented on src/world.rs
>              components.put(|ptr, ty| {
This isn't an improvement.

2022-05-05 03:45 UTC, Ralith commented on src/world.rs
>              components.put(|ptr, ty| {
Oh, I see the point, nevermind.

2022-05-09 01:34 UTC, peamaeq commented on src/archetype.rs
> +        self.data = new_data;
Sorry for the long reply, there is no borrowck issue here.

2022-05-09 03:45 UTC, Ralith commented
Thanks!

2022-05-09 03:47 UTC, merged