Implement iter_batched for QueryMut
Ralith/hecs pull request #281
Opened 2022-08-14 18:42 UTC by Uriopass

Skips the borrow checking

2022-08-14 20:59 UTC, Uriopass commented
The CI test failing talked about an error message unrelated to the PR that looked like it changed in the latest Rust, fixed it in [another commit](https://github.com/Ralith/hecs/pull/281/commits/11dbef93655c345cf8759d528372dc195b5cecc9).

2022-08-14 23:31 UTC, Ralith requested changes
Thanks!

2022-08-14 23:31 UTC, Ralith commented on src/query.rs
> +    pub fn iter_batched(self, batch_size: u32) -> BatchedIter<'q, Q> {
Since this takes ownership of `self`:
```suggestion
    pub fn into_iter_batched(self, batch_size: u32) -> BatchedIter<'q, Q> {
```

2022-08-15 06:35 UTC, Uriopass commented on src/query.rs
> +    pub fn iter_batched(self, batch_size: u32) -> BatchedIter<'q, Q> {
Done!

2022-08-15 14:41 UTC, Ralith approved these changes

2022-08-15 14:41 UTC, merged